### ISSUE TITLE
Uncaught TypeError: Cannot set property 'updateTilesState' of undefined

### ISSUE THREAD

**Issue by Femrebil** [franekp/atom-inspect-python#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.1
**Thrown From**: [inspect-python](https://github.com/franekp/atom-inspect-python) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot set property 'updateTilesState' of undefined

```
At /Users/emrebil/.atom/packages/inspect-python/lib/inspect-python.coffee:7

TypeError: Cannot set property 'updateTilesState' of undefined
    at monkey_patch (/packages/inspect-python/lib/inspect-python.coffee:7:3)
    at Object.openDefinition (/packages/inspect-python/lib/inspect-python.coffee:157:5)
    at Object.callback (/packages/inspect-python/lib/hyperclick-provider.coffee:12:23)
    at HyperclickForTextEditor._confirmSuggestion (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:183:18)
    at HyperclickForTextEditor._onMouseDown (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:247:12)
```

### Commands

```
  7x -9:02.8.0 core:backspace (input.hidden-input)
     -8:55.7.0 core:confirm (input.hidden-input)
 12x -8:54.3.0 core:backspace (input.hidden-input)
  3x -7:30.9.0 python-tools:goto-definition (span.syntax--keyword.syntax--control)
  2x -6:51.1.0 datatip:toggle (input.hidden-input)
     -6:50.4.0 hydrogen:run-cell (input.hidden-input)
     -6:50.1.0 datatip:toggle (input.hidden-input)
  6x -5:06.9.0 core:backspace (input.hidden-input)
  7x -4:40.4.0 goto-definition:go (span.syntax--entity.syntax--name.syntax--function)
  2x -2:03.0 datatip:toggle (input.hidden-input)
     -0:09.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-python-run 0.9.7 
atom-python-test 0.10.0 
atom-runner 2.7.1 
autocomplete-python 1.11.0 
build 0.70.0 
build-python 0.9.3 
busy-signal 1.4.3 
goto-definition 1.3.4 
Hydrogen 2.6.0 
ide-python 1.0.0 
inspect-python 0.1.0 
python-debugger 0.2.0 
python-indent 1.1.6 
python-isort 0.0.7 
python-line-profiler 0.3.2 
python-snippets 1.9.0 
python-tools 0.6.9 
run-python-simply 0.4.0 
```

**Comment by gilbertohasnofb** [comment]
Running into the same issue on Linux and Atom 1.40.1
